---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-kernel
spec:
  template:
    spec:
      containers:
        - name: nse
          env:
            - name: NSM_CIDR_PREFIX
              value: 172.16.2.0/31
            - name: NSM_SERVICE_NAMES
              value: "enforcment-scenario"
            - name: NSM_REGISTER_SERVICE
              value: "false"
            - name: NSM_LABELS
              value: "app:gateway"
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
          - containerPort: 8080
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          imagePullPolicy: IfNotPresent
        - name: tcpdump
          image: corfr/tcpdump
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
              - NET_RAW
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config

